# Generated by Django 4.1.3 on 2024-01-09 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bangazonapi', '0003_alter_order_close_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='close_time',
            field=models.DateTimeField(default='null', null=True),
        ),
    ]
