# Generated by Django 4.1.3 on 2024-01-13 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bangazonapi', '0005_alter_order_close_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='open',
            new_name='is_open',
        ),
    ]
